### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by CmdrHope** [rfvgyhn/min-ed-launcher#66]
I am using the Epic Games Version of Elite Dangerous with Lutris, which works fine. However when I try to run it with min-ed-launcher it always fails with an unhandled exception in the logfile (attached).

[min-ed-launcher.log](https://github.com/rfvgyhn/min-ed-launcher/files/9710129/min-ed-launcher.log)

**Comment by rfvgyhn** [comment]
Am I correct in assuming lutris launches the epic game store, then you launch elite from there (or does it launch elite directly)? If so, I also assume you followed the Epic install steps, right? Does renaming `MinEdLauncher.exe` to `EDLaunch.exe` instead of `MinEdLauncher.Bootstrapper.exe` give a different result?

**Comment by CmdrHope** [comment]
When I launch Elite with Lutris, it actually launches the Epic Games Store within Wine (`EpicGamesLauncher.exe` with the arguments `-opengl -SkipBuildPatchPrereq -com.epicgames.launcher://apps/9c203b6ed35846e8a4a9ff1e314f6593?action=launch`) which then tries to launch Elite.

I tried both `MinEdLauncher.Bootstrapper.exe` and `MinEdLauncher.exe` renamed to `EDLaunch.exe` with the same error as result.

I tried using several different wine versions in Lutris but that didn't change the result.

I even tried to install the Windows version of Legendary into the existing wine prefix and configured Lutris to run `legendary.exe launch 9c203b6ed35846e8a4a9ff1e314f6593 --override-exe MinEdLauncher.exe /autorun /edh /autoquit` which fails with the exact same error in the logfile.

**Comment by rfvgyhn** [comment]
Do older versions have the same issue? Does using the [linux version of legendary and min-ed-launcher](https://github.com/rfvgyhn/min-ed-launcher#linux) have the same issue? Trying to figure out if lutris does something I haven't accounted for or if something else is going on.

**Comment by CmdrHope** [comment]
I tried the versions v0.7.1, v0.7.0, v0.6.0 and v0.5.4 and attached the resulting logfile.
[min-ed-launcher.log](https://github.com/rfvgyhn/min-ed-launcher/files/9719049/min-ed-launcher.log)

v0.7.1 and v0.7.0 produce the same error. In v0.6.0 the error happens in line 58 instead of line 59. And v0.5.4 fails without even writing anything into the logfile.

Regarding the method you described [here](https://github.com/rfvgyhn/min-ed-launcher#linux), I have no idea how to configure that in Lutris. And setting up games in Linux without Steam or Lutris is a topic I haven't looked into, yet, sorry.

**Comment by rfvgyhn** [comment]
This is fixed and will be included in the next release. You can use the [CI build](https://github.com/rfvgyhn/min-ed-launcher/actions/runs/3201036258) build until then if you'd like. If you do, you'll want to use the new bootstrapper exe. You'll also probably want to change the font of the cmd window in wine to something like consolas.

**Comment by CmdrHope** [comment]
I tried the new build, the error is gone and the [min-ed-launcher.log](https://github.com/rfvgyhn/min-ed-launcher/files/9740117/min-ed-launcher.log) doesn't seem to have any complaints. However the game still doesn't start.

**Comment by rfvgyhn** [comment]
* Does the launcher just quit or does it just stop writing to the log file?
* Does it always fail in the same spot?
* Does it have the same issue if you remove the `/autorun` flag?
* Which version of wine are you using?
* Which lutris installer did you use? I couldn't get any of the provided ones to work and had to cobble together my own. It's possible there's some wine environment difference that I don't have locally.
* What game options do you have setup in lutris?
* I added some additional logging. Can you try the [CI build](https://github.com/rfvgyhn/min-ed-launcher/actions/runs/3212048130) and post the new log?

That log file looks like #59. Can we take the conversation there?
